[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "midi-utils"
version = "0.1.0"
description = "Simple utilities to convert between MIDI note numbers and note names."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "librosa",
    "torchaudio",
    "soundfile",
    "mido",
    "requests",
]
