#!/usr/bin/env python
"""Side-by-side benchmark of generation backends on the same prompts.

Runs each prompt through the deterministic backend and the Stage 2 n-gram
melody backend, computes the evaluation-metric suite on each result, and
prints a Markdown table. This is a *comparison*, not a victory lap: the
n-gram model's demo corpus is synthetic data generated by the deterministic
backend itself, so these numbers characterise the trade-offs of the
statistical baseline — they cannot show that it "beats" the rules, and no
such claim should be read into them.

Usage:
    python scripts/compare_backends.py
    python scripts/compare_backends.py --prompt "trap melody with dark bells" --bars 8
    python scripts/compare_backends.py --output benchmark.md
"""

from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence

# Allow running straight from a checkout without an editable install.
_SRC = Path(__file__).resolve().parent.parent / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

import mido

from creative_audio_lab.evaluation import evaluate_arrangement
from creative_audio_lab.evaluation.metrics import motif_retention_score
from creative_audio_lab.export import export_arrangement_files
from creative_audio_lab.models import get_backend

BACKEND_NAMES = ("deterministic", "ngram_melody")

DEFAULT_PROMPTS = (
    "dark orchestral boss battle theme, 140 BPM, brass ostinato, strings, piano arps",
    "romantic piano loop in C minor, 90 BPM",
    "trap melody with dark bells and sliding bass",
    "nostalgic JRPG town theme with piano and flute",
)

#: Metric columns shown per row, in order. All but the last two come from
#: evaluate_arrangement; motif retention is measured against the
#: deterministic melody for the same prompt.
COLUMNS = (
    "note_density",
    "harmonic_fit_score",
    "novelty_score",
    "repetition_score",
    "scale_adherence_score",
    "motif_retention",
    "melody_notes",
    "midi_valid",
)


def midi_export_is_valid(arrangement) -> bool:
    """Export the arrangement and re-parse every file with mido."""
    try:
        files = export_arrangement_files(arrangement)
        for data in files.values():
            mido.MidiFile(file=io.BytesIO(data))
        return True
    except Exception:
        return False


def benchmark_prompt(prompt: str, bars: Optional[int] = None) -> List[Dict[str, object]]:
    """Run ``prompt`` through every backend and collect one metrics row each."""
    deterministic_melody = None
    rows: List[Dict[str, object]] = []
    for backend_name in BACKEND_NAMES:
        arrangement = get_backend(backend_name).generate(prompt, bars=bars)
        melody = arrangement.parts.get("melody", [])
        if backend_name == "deterministic":
            deterministic_melody = melody
        metrics = evaluate_arrangement(arrangement)
        # Motif retention only applies relative to a reference line; we use
        # the deterministic melody for the same prompt (1.0 for itself).
        retention = (
            motif_retention_score(deterministic_melody, melody)
            if deterministic_melody
            else float("nan")
        )
        rows.append(
            {
                "prompt": prompt,
                "backend": backend_name,
                "note_density": metrics["note_density"],
                "harmonic_fit_score": metrics["harmonic_fit_score"],
                "novelty_score": metrics["novelty_score"],
                "repetition_score": metrics["repetition_score"],
                "scale_adherence_score": metrics["scale_adherence_score"],
                "motif_retention": retention,
                "melody_notes": len(melody),
                "midi_valid": midi_export_is_valid(arrangement),
            }
        )
    return rows


def _format_cell(value: object) -> str:
    if isinstance(value, bool):
        return "yes" if value else "NO"
    if isinstance(value, float):
        return f"{value:.3f}"
    return str(value)


def render_markdown(rows: Sequence[Dict[str, object]]) -> str:
    """Render benchmark rows as a Markdown table grouped by prompt."""
    lines = ["| prompt | backend | " + " | ".join(COLUMNS) + " |"]
    lines.append("|" + " --- |" * (len(COLUMNS) + 2))
    for row in rows:
        prompt = str(row["prompt"])
        shown_prompt = prompt if len(prompt) <= 48 else prompt[:45] + "..."
        cells = [shown_prompt, str(row["backend"])] + [_format_cell(row[c]) for c in COLUMNS]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--prompt",
        action="append",
        dest="prompts",
        help="Prompt to benchmark (repeatable; defaults to a built-in set)",
    )
    parser.add_argument("--bars", type=int, default=None, help="Override bar count for every run")
    parser.add_argument("--output", default=None, help="Also write the Markdown table to this file")
    args = parser.parse_args(argv)

    prompts = args.prompts or list(DEFAULT_PROMPTS)
    rows: List[Dict[str, object]] = []
    for prompt in prompts:
        rows.extend(benchmark_prompt(prompt, bars=args.bars))

    table = render_markdown(rows)
    print("# Backend comparison\n")
    print(table)
    print(
        "\nNotes: metrics are proxy statistics, not judgments of musical quality. "
        "The n-gram demo model is bootstrap-trained on synthetic melodies produced "
        "by the deterministic backend, so this table characterises trade-offs — "
        "it is not evidence that either backend is 'better'."
    )
    if args.output:
        Path(args.output).write_text(table + "\n", encoding="utf-8")
        print(f"\nTable written to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
