"""Training utilities for the Stage 2 N-gram melody baseline.

Two corpora are supported. Without a manifest, the corpus is **synthetic
bootstrap data**: melodies generated by
the existing :class:`~creative_audio_lab.models.DeterministicBackend` across
a grid of prompts, keys, and BPMs. That makes the N-gram backend a real
*statistical* model (it samples from fitted counts, not rules) while staying
honest about what it learned from — its training distribution is this
project's own rule-based generator, so it demonstrates the training/sampling
machinery, **not** musical generalisation. Nothing is downloaded; to train
on real music, pass your own licensed token sequences (e.g. produced via
``creative_audio_lab.data``'s local-only loader + provenance validation and
the symbolic tokenizer) to :func:`train_ngram_model`.

Melodies are transposed to a common C root before counting so pitch
statistics pool across keys instead of memorising one key's line, and only
the ``NOTE_ON``/``VELOCITY``/``DURATION`` sub-stream is modelled — timing
anchors (``BAR``/``POSITION``) are reconstructed deterministically at decode
time by the backend, which keeps every sampled sequence decodable.

With ``--manifest``, the corpus comes from
:func:`creative_audio_lab.data.corpus_pipeline.build_corpus`: a
rights-checked local MIDI collection, split at the composition level, with
held-out cross-entropy reported on the val and test splits. Either way the
CLI writes a *training artefact* — the model plus the metadata (corpus
identity and licences, split assignment, tokenizer config, seeds, software
versions, corpus statistics, held-out metrics) that any claim about the
model depends on.

Run::

    python scripts/train_ngram_melody.py --output model.json
    python scripts/train_ngram_melody.py --manifest datasets.json --output real.json
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

from ..data.corpus_pipeline import SPLIT_NAMES
from ..music_theory import Note, note_name_to_pitch_class
from ..tokenization import SymbolicTokenizer
from ..tokenization.token_types import TokenType
from .deterministic_backend import DeterministicBackend
from .ngram_model import NGramModel
from .note_event_model import (
    DEFAULT_DURATION_ORDER,
    DEFAULT_PITCH_ORDER,
    DEFAULT_VELOCITY_ORDER,
    MelodyModel,
    NoteEventModel,
)

#: Token types the melody model is trained on; BAR/POSITION are rebuilt at decode time.
MELODY_TOKEN_TYPES = (TokenType.NOTE_ON, TokenType.VELOCITY, TokenType.DURATION)

#: Default prompt grid: one prompt per style preset the parser knows about.
BOOTSTRAP_PROMPTS: Tuple[str, ...] = (
    "dark orchestral boss battle theme with brass and strings",
    "cinematic trailer cue with strings and piano",
    "trap melody with dark bells and sliding bass",
    "drill beat with bells and heavy bass",
    "calm ambient piano and strings",
    "nostalgic jrpg town theme with piano and flute",
    "romantic piano ballad",
    "hopeful piano and strings theme",
)

BOOTSTRAP_KEYS: Tuple[str, ...] = ("C", "D", "E", "F", "G", "A")
BOOTSTRAP_BPMS: Tuple[Optional[int], ...] = (None, 90, 140)

#: Order of the *flat* interleaved model (kept for comparison; see note below).
DEFAULT_ORDER = 3

#: Model kinds: ``"factorised"`` (default) predicts each note attribute from
#: its own history — pitch from previous pitches — while ``"flat"`` is the
#: original single n-gram over the interleaved token stream, whose order-3
#: default never saw the previous pitch when predicting the next one.
MODEL_KINDS = ("factorised", "flat")
DEFAULT_MODEL_KIND = "factorised"


def transpose_notes(notes: Sequence[Note], semitones: int) -> List[Note]:
    """Return ``notes`` shifted by ``semitones``, clamped to the MIDI range."""
    return [
        Note(
            start=note.start,
            pitch=min(max(note.pitch + semitones, 0), 127),
            duration=note.duration,
            velocity=note.velocity,
        )
        for note in notes
    ]


def melody_token_stream(
    notes: Sequence[Note], tokenizer: Optional[SymbolicTokenizer] = None
) -> List[str]:
    """Encode ``notes`` and keep only the NOTE_ON/VELOCITY/DURATION sub-stream."""
    tokenizer = tokenizer or SymbolicTokenizer()
    return [
        token.to_string()
        for token in tokenizer.encode(notes)
        if token.type in MELODY_TOKEN_TYPES
    ]


def build_bootstrap_corpus(
    prompts: Sequence[str] = BOOTSTRAP_PROMPTS,
    keys: Sequence[str] = BOOTSTRAP_KEYS,
    bpms: Sequence[Optional[int]] = BOOTSTRAP_BPMS,
) -> List[List[str]]:
    """Generate the synthetic melody-token corpus from the deterministic backend.

    Every (prompt, key, bpm) combination is generated once, the melody part is
    transposed to a C root, and encoded to a token stream. This is bootstrap
    data — a stand-in distribution that exercises the training path, not a
    claim of learning from real music.
    """
    backend = DeterministicBackend()
    tokenizer = SymbolicTokenizer()
    corpus: List[List[str]] = []
    for prompt in prompts:
        for key in keys:
            for bpm in bpms:
                arrangement = backend.generate(prompt, key=key, bpm=bpm)
                melody = arrangement.parts.get("melody", [])
                if not melody:
                    continue
                root_pc = note_name_to_pitch_class(arrangement.controls.key)
                normalized = transpose_notes(melody, -root_pc)
                stream = melody_token_stream(normalized, tokenizer)
                if stream:
                    corpus.append(stream)
    return corpus


def train_ngram_model(
    sequences: Iterable[Sequence[str]], order: int = DEFAULT_ORDER
) -> NGramModel:
    """Fit a *flat* :class:`NGramModel` of ``order`` on interleaved token ``sequences``."""
    return NGramModel(order=order).fit(sequences)


def train_melody_model(
    sequences: Iterable[Sequence[str]],
    kind: str = DEFAULT_MODEL_KIND,
    *,
    order: Optional[int] = None,
    duration_order: int = DEFAULT_DURATION_ORDER,
    velocity_order: int = DEFAULT_VELOCITY_ORDER,
) -> MelodyModel:
    """Fit a melody model of ``kind`` on interleaved note-token ``sequences``.

    ``order`` is the flat model's n-gram order, or the pitch sub-model's
    order for the factorised kind (default 3 = two previous pitches).
    """
    if kind == "factorised":
        return NoteEventModel(
            pitch_order=DEFAULT_PITCH_ORDER if order is None else order,
            duration_order=duration_order,
            velocity_order=velocity_order,
        ).fit(sequences)
    if kind == "flat":
        return train_ngram_model(sequences, order=DEFAULT_ORDER if order is None else order)
    raise ValueError(f"Unknown model kind {kind!r}; expected one of {MODEL_KINDS}")


def train_bootstrap_model(
    order: Optional[int] = None, kind: str = DEFAULT_MODEL_KIND, **kwargs
) -> MelodyModel:
    """Train the default demo model on the synthetic bootstrap corpus."""
    return train_melody_model(build_bootstrap_corpus(), kind, order=order, **kwargs)


def format_metrics(metrics: Dict[str, float]) -> str:
    """One-line summary of a held-out evaluation result."""
    if not metrics or not metrics.get("notes"):
        return "no held-out notes"
    return (
        f"{metrics['notes']} notes | {metrics['bits_per_note']:.3f} bits/note "
        f"(pitch {metrics['pitch_bits_per_note']:.3f}, "
        f"velocity {metrics['velocity_bits_per_note']:.3f}, "
        f"duration {metrics['duration_bits_per_note']:.3f}) | "
        f"perplexity {metrics['perplexity_per_note']:.1f} | "
        f"pitch OOV {metrics['pitch_oov_rate']:.3f}"
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Train a Stage 2 melody model and save it as a training artefact. "
            "Without --manifest the corpus is synthetic bootstrap data generated "
            "by the deterministic backend (nothing is downloaded); with "
            "--manifest it is your own rights-checked local MIDI corpus."
        )
    )
    parser.add_argument("--output", required=True, help="Path for the JSON artefact")
    parser.add_argument(
        "--manifest",
        default=None,
        help="Dataset manifest describing a local, rights-cleared MIDI corpus",
    )
    parser.add_argument(
        "--eval-manifest",
        default=None,
        help="Evaluate on this corpus's held-out splits instead of the training corpus "
        "(use it to score a bootstrap-trained model on real music)",
    )
    parser.add_argument(
        "--model-kind", choices=MODEL_KINDS, default=DEFAULT_MODEL_KIND,
        help="factorised (default): each note attribute is predicted from its own "
        "history, so pitch is conditioned on previous pitches. flat: one n-gram "
        "over the interleaved token stream",
    )
    parser.add_argument(
        "--order", type=int, default=None,
        help="Pitch sub-model order (factorised) or n-gram order (flat); default 3",
    )
    parser.add_argument("--duration-order", type=int, default=DEFAULT_DURATION_ORDER)
    parser.add_argument("--velocity-order", type=int, default=DEFAULT_VELOCITY_ORDER)
    parser.add_argument(
        "--intended-use", choices=("research", "commercial"), default="research",
        help="Licence policy applied to every manifest entry (default research)",
    )
    parser.add_argument(
        "--time-signature", action="append", dest="time_signatures", default=None,
        help="Allowed time signature, repeatable (default 4/4); pass 'any' to accept all",
    )
    parser.add_argument("--split-seed", type=int, default=0)
    parser.add_argument("--val-fraction", type=float, default=0.1)
    parser.add_argument("--test-fraction", type=float, default=0.1)
    parser.add_argument("--min-notes", type=int, default=16)
    parser.add_argument(
        "--allow-reference-only", action="store_true",
        help="Ingest entries that fail the rights check as held-out evaluation "
        "material only; they can never enter the training split",
    )
    return parser


def corpus_config_from_args(args: argparse.Namespace):
    """Build a :class:`CorpusConfig` from parsed CLI arguments."""
    from ..data import CorpusConfig

    signatures = args.time_signatures
    if signatures is None:
        signatures = ("4/4",)
    elif any(value.lower() == "any" for value in signatures):
        signatures = None
    else:
        signatures = tuple(signatures)
    train_fraction = 1.0 - args.val_fraction - args.test_fraction
    if train_fraction <= 0:
        raise SystemExit("--val-fraction and --test-fraction must leave room for training data")
    return CorpusConfig(
        intended_use=args.intended_use,
        time_signatures=signatures,
        min_notes=args.min_notes,
        fractions=(train_fraction, args.val_fraction, args.test_fraction),
        split_seed=args.split_seed,
        allow_reference_only=args.allow_reference_only,
    )


def _corpus_metadata(bundle, manifest_path: str) -> Dict[str, Any]:
    return {
        "source": "manifest",
        "manifest_path": str(Path(manifest_path).resolve()),
        "datasets": bundle.datasets,
        "intended_use": bundle.config.intended_use,
        "filters": {
            "time_signatures": list(bundle.config.time_signatures or []) or "any",
            "min_notes": bundle.config.min_notes,
            "max_polyphony_ratio": bundle.config.max_polyphony_ratio,
            "grid": bundle.config.grid,
            "transpose_to_tonic": bundle.config.transpose_to_tonic,
        },
        "provenance_report": bundle.provenance_report,
        "rejections": [{"composition_id": cid, "reason": reason} for cid, reason in bundle.rejections],
        "corpus_hash": bundle.corpus_hash,
    }


def main(argv: Optional[Sequence[str]] = None) -> int:
    """CLI: train a melody model and save it with its full training metadata."""
    from ..data import build_corpus
    from ..tokenization import TokenizerConfig
    from .artefact import save_artefact
    from .note_event_model import evaluate_melody_model

    args = build_parser().parse_args(argv)
    tokenizer_config = TokenizerConfig()

    if args.manifest:
        bundle = build_corpus(args.manifest, corpus_config_from_args(args))
        train_sequences = bundle.sequences("train")
        corpus_meta = _corpus_metadata(bundle, args.manifest)
        split_meta = {
            "seed": bundle.config.split_seed,
            "fractions": list(bundle.config.fractions),
            "level": "composition",
            "compositions": {name: bundle.composition_ids(name) for name in SPLIT_NAMES},
        }
        stats = bundle.stats()
    else:
        train_sequences = build_bootstrap_corpus()
        corpus_meta = {
            "source": "synthetic-bootstrap",
            "note": "Melodies generated by this project's own deterministic backend. "
            "Exercises the training path; says nothing about real musical "
            "generalisation.",
            "prompts": list(BOOTSTRAP_PROMPTS),
            "keys": list(BOOTSTRAP_KEYS),
            "bpms": list(BOOTSTRAP_BPMS),
        }
        split_meta = {"level": "none", "note": "synthetic corpus is not split"}
        stats = {
            "splits": {"train": {"pieces": len(train_sequences),
                                 "tokens": sum(len(s) for s in train_sequences)}},
        }

    model = train_melody_model(
        train_sequences, args.model_kind, order=args.order,
        duration_order=args.duration_order, velocity_order=args.velocity_order,
    )

    # Held-out evaluation: the training corpus's own splits, or another
    # corpus entirely (e.g. scoring the synthetic model on real music).
    metrics: Dict[str, Any] = {}
    eval_source = None
    if args.eval_manifest:
        eval_bundle = build_corpus(args.eval_manifest, corpus_config_from_args(args))
        eval_source = str(Path(args.eval_manifest).resolve())
        for split in ("val", "test"):
            metrics[split] = evaluate_melody_model(model, eval_bundle.sequences(split))
    elif args.manifest:
        eval_source = corpus_meta["manifest_path"]
        for split in ("val", "test"):
            metrics[split] = evaluate_melody_model(model, bundle.sequences(split))
    metrics["train"] = evaluate_melody_model(model, train_sequences)

    metadata = {
        "corpus": corpus_meta,
        "split": split_meta,
        "tokenizer": {
            "beats_per_bar": tokenizer_config.beats_per_bar,
            "positions_per_beat": tokenizer_config.positions_per_beat,
            "velocity_bins": tokenizer_config.velocity_bins,
            "max_duration_beats": tokenizer_config.max_duration_beats,
        },
        "seeds": {
            "split_seed": args.split_seed,
            "sampling": "derived per prompt from the resolved controls (see ngram_backend)",
        },
        "stats": stats,
        "metrics": metrics,
        "evaluated_on": eval_source,
    }
    path = save_artefact(model, metadata, args.output)

    print(f"Trained {args.model_kind} melody model on {len(train_sequences)} sequences")
    print(f"Corpus: {corpus_meta['source']}")
    if args.manifest:
        for name in SPLIT_NAMES:
            split_stats = stats["splits"][name]
            print(f"  {name:5s} {split_stats['pieces']:4d} pieces, {split_stats['notes']:6d} notes")
        print(f"  rejected {stats['rejected_pieces']} pieces: {stats['rejection_reasons']}")
    for split, values in metrics.items():
        print(f"  {split:5s} {format_metrics(values)}")
    print(f"Saved artefact to {path}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())


__all__ = [
    "MELODY_TOKEN_TYPES",
    "BOOTSTRAP_PROMPTS",
    "BOOTSTRAP_KEYS",
    "BOOTSTRAP_BPMS",
    "DEFAULT_ORDER",
    "MODEL_KINDS",
    "DEFAULT_MODEL_KIND",
    "transpose_notes",
    "melody_token_stream",
    "build_bootstrap_corpus",
    "train_ngram_model",
    "train_melody_model",
    "train_bootstrap_model",
    "build_parser",
    "corpus_config_from_args",
    "format_metrics",
    "main",
]
