"""Training utilities for the Stage 2 N-gram melody baseline.

The corpus built here is **synthetic bootstrap data**: melodies generated by
the existing :class:`~creative_audio_lab.models.DeterministicBackend` across
a grid of prompts, keys, and BPMs. That makes the N-gram backend a real
*statistical* model (it samples from fitted counts, not rules) while staying
honest about what it learned from — its training distribution is this
project's own rule-based generator, so it demonstrates the training/sampling
machinery, **not** musical generalisation. Nothing is downloaded; to train
on real music, pass your own licensed token sequences (e.g. produced via
``creative_audio_lab.data``'s local-only loader + provenance validation and
the symbolic tokenizer) to :func:`train_ngram_model`.

Melodies are transposed to a common C root before counting so pitch
statistics pool across keys instead of memorising one key's line, and only
the ``NOTE_ON``/``VELOCITY``/``DURATION`` sub-stream is modelled — timing
anchors (``BAR``/``POSITION``) are reconstructed deterministically at decode
time by the backend, which keeps every sampled sequence decodable.

Run ``python scripts/train_ngram_melody.py --output model.json`` to write a
reusable JSON model.
"""

from __future__ import annotations

import argparse
from typing import Iterable, List, Optional, Sequence, Tuple

from ..music_theory import Note, note_name_to_pitch_class
from ..tokenization import SymbolicTokenizer
from ..tokenization.token_types import TokenType
from .deterministic_backend import DeterministicBackend
from .ngram_model import NGramModel

#: Token types the melody model is trained on; BAR/POSITION are rebuilt at decode time.
MELODY_TOKEN_TYPES = (TokenType.NOTE_ON, TokenType.VELOCITY, TokenType.DURATION)

#: Default prompt grid: one prompt per style preset the parser knows about.
BOOTSTRAP_PROMPTS: Tuple[str, ...] = (
    "dark orchestral boss battle theme with brass and strings",
    "cinematic trailer cue with strings and piano",
    "trap melody with dark bells and sliding bass",
    "drill beat with bells and heavy bass",
    "calm ambient piano and strings",
    "nostalgic jrpg town theme with piano and flute",
    "romantic piano ballad",
    "hopeful piano and strings theme",
)

BOOTSTRAP_KEYS: Tuple[str, ...] = ("C", "D", "E", "F", "G", "A")
BOOTSTRAP_BPMS: Tuple[Optional[int], ...] = (None, 90, 140)

DEFAULT_ORDER = 3


def transpose_notes(notes: Sequence[Note], semitones: int) -> List[Note]:
    """Return ``notes`` shifted by ``semitones``, clamped to the MIDI range."""
    return [
        Note(
            start=note.start,
            pitch=min(max(note.pitch + semitones, 0), 127),
            duration=note.duration,
            velocity=note.velocity,
        )
        for note in notes
    ]


def melody_token_stream(
    notes: Sequence[Note], tokenizer: Optional[SymbolicTokenizer] = None
) -> List[str]:
    """Encode ``notes`` and keep only the NOTE_ON/VELOCITY/DURATION sub-stream."""
    tokenizer = tokenizer or SymbolicTokenizer()
    return [
        token.to_string()
        for token in tokenizer.encode(notes)
        if token.type in MELODY_TOKEN_TYPES
    ]


def build_bootstrap_corpus(
    prompts: Sequence[str] = BOOTSTRAP_PROMPTS,
    keys: Sequence[str] = BOOTSTRAP_KEYS,
    bpms: Sequence[Optional[int]] = BOOTSTRAP_BPMS,
) -> List[List[str]]:
    """Generate the synthetic melody-token corpus from the deterministic backend.

    Every (prompt, key, bpm) combination is generated once, the melody part is
    transposed to a C root, and encoded to a token stream. This is bootstrap
    data — a stand-in distribution that exercises the training path, not a
    claim of learning from real music.
    """
    backend = DeterministicBackend()
    tokenizer = SymbolicTokenizer()
    corpus: List[List[str]] = []
    for prompt in prompts:
        for key in keys:
            for bpm in bpms:
                arrangement = backend.generate(prompt, key=key, bpm=bpm)
                melody = arrangement.parts.get("melody", [])
                if not melody:
                    continue
                root_pc = note_name_to_pitch_class(arrangement.controls.key)
                normalized = transpose_notes(melody, -root_pc)
                stream = melody_token_stream(normalized, tokenizer)
                if stream:
                    corpus.append(stream)
    return corpus


def train_ngram_model(
    sequences: Iterable[Sequence[str]], order: int = DEFAULT_ORDER
) -> NGramModel:
    """Fit an :class:`NGramModel` of ``order`` on token ``sequences``."""
    return NGramModel(order=order).fit(sequences)


def train_bootstrap_model(order: int = DEFAULT_ORDER) -> NGramModel:
    """Train the default demo model on the synthetic bootstrap corpus."""
    return train_ngram_model(build_bootstrap_corpus(), order=order)


def main(argv: Optional[Sequence[str]] = None) -> int:
    """CLI: train the bootstrap model and save it as JSON."""
    parser = argparse.ArgumentParser(
        description=(
            "Train the Stage 2 N-gram melody model on a synthetic bootstrap "
            "corpus generated by the deterministic backend (nothing is "
            "downloaded), and save it as JSON."
        )
    )
    parser.add_argument("--output", required=True, help="Path for the JSON model file")
    parser.add_argument("--order", type=int, default=DEFAULT_ORDER, help="N-gram order (default 3)")
    args = parser.parse_args(argv)

    model = train_bootstrap_model(order=args.order)
    path = model.save_json(args.output)
    print(
        f"Saved order-{model.order} n-gram model "
        f"({model.total_tokens} training tokens, {len(model.vocabulary)} token vocab) "
        f"to {path}"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())


__all__ = [
    "MELODY_TOKEN_TYPES",
    "BOOTSTRAP_PROMPTS",
    "BOOTSTRAP_KEYS",
    "BOOTSTRAP_BPMS",
    "DEFAULT_ORDER",
    "transpose_notes",
    "melody_token_stream",
    "build_bootstrap_corpus",
    "train_ngram_model",
    "train_bootstrap_model",
    "main",
]
